### ISSUE TITLE
Vagrantfile für Entwicklung hinzufügen

### ISSUE THREAD

**Issue by haogatyp** [OPUS4/opus4-doi#7]
Mit Vagrant lässt sich eine Entwicklungsumgebung in einer VM hochfahren, so dass die notwendigen Tools und Ressourcen nicht im Host-System installiert werden müssen.

**Comment by j3nsch** [comment]
Sieht gut aus! Danke!

**Comment by j3nsch** [comment]
Wenn wir Composer mit `apt-get` installieren, bekommen wir Version 1.x und benötigen außerdem `php7.1-mbstring`. Ansonsten wirft `composer -v` einen Fehler. Die bessere Alternative ist vermutlich Composer so wie im Framework Vagrantfile zu installieren, einschließlich der Ergänzungen zu .bashrc, so dass `composer` verwendet werden kann.
